services:
  - type: web
    name: django-web
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn myproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      # Optional: configure a database URL if you're using PostgreSQL
      - fromDatabase:
          name: my-db
          property: connectionString
          key: DATABASE_URL
